version: 0.0
os: linux
files:
  - source: app.jar
    destination: /opt/app
  - source: scripts/
    destination: /opt/app/scripts/
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 20
      runas: root

