version: 0.0
os: linux
files:
  - source: /
    destination: /opt/app
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 20
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 20

