version: 0.0
os: linux
files:
  - source: target/spring-boot-hello-world-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 60
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 60

